/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVaultSuggestRouteImport } from './routes/api/vault-suggest'
import { Route as ApiSpiralsAnalyzeRouteImport } from './routes/api/spirals-analyze'
import { Route as ApiInsightsGenerateRouteImport } from './routes/api/insights-generate'
import { Route as ApiFoundationReflectionRouteImport } from './routes/api/foundation-reflection'
import { Route as ApiAceRouteImport } from './routes/api/ace'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedSpiralsRouteImport } from './routes/_authenticated/spirals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNourishRouteImport } from './routes/_authenticated/nourish'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedFoundationRouteImport } from './routes/_authenticated/foundation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrainRouteImport } from './routes/_authenticated/brain'
import { Route as AuthenticatedAceRouteImport } from './routes/_authenticated/ace'
import { Route as ApiGocardlessCallbackRouteImport } from './routes/api/gocardless.callback'
import { Route as ApiPublicHooksSendNotificationsRouteImport } from './routes/api/public/hooks/send-notifications'
import { Route as ApiPublicHooksRefreshCustomDealsRouteImport } from './routes/api/public/hooks/refresh-custom-deals'
import { Route as ApiPublicHooksNotificationOpenedRouteImport } from './routes/api/public/hooks/notification-opened'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultSuggestRoute = ApiVaultSuggestRouteImport.update({
  id: '/api/vault-suggest',
  path: '/api/vault-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpiralsAnalyzeRoute = ApiSpiralsAnalyzeRouteImport.update({
  id: '/api/spirals-analyze',
  path: '/api/spirals-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsGenerateRoute = ApiInsightsGenerateRouteImport.update({
  id: '/api/insights-generate',
  path: '/api/insights-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoundationReflectionRoute = ApiFoundationReflectionRouteImport.update({
  id: '/api/foundation-reflection',
  path: '/api/foundation-reflection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAceRoute = ApiAceRouteImport.update({
  id: '/api/ace',
  path: '/api/ace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpiralsRoute = AuthenticatedSpiralsRouteImport.update({
  id: '/spirals',
  path: '/spirals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNourishRoute = AuthenticatedNourishRouteImport.update({
  id: '/nourish',
  path: '/nourish',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFoundationRoute = AuthenticatedFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrainRoute = AuthenticatedBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAceRoute = AuthenticatedAceRouteImport.update({
  id: '/ace',
  path: '/ace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiGocardlessCallbackRoute = ApiGocardlessCallbackRouteImport.update({
  id: '/api/gocardless/callback',
  path: '/api/gocardless/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendNotificationsRoute =
  ApiPublicHooksSendNotificationsRouteImport.update({
    id: '/api/public/hooks/send-notifications',
    path: '/api/public/hooks/send-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshCustomDealsRoute =
  ApiPublicHooksRefreshCustomDealsRouteImport.update({
    id: '/api/public/hooks/refresh-custom-deals',
    path: '/api/public/hooks/refresh-custom-deals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationOpenedRoute =
  ApiPublicHooksNotificationOpenedRouteImport.update({
    id: '/api/public/hooks/notification-opened',
    path: '/api/public/hooks/notification-opened',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ace': typeof AuthenticatedAceRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/foundation': typeof AuthenticatedFoundationRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/nourish': typeof AuthenticatedNourishRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spirals': typeof AuthenticatedSpiralsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/api/ace': typeof ApiAceRoute
  '/api/foundation-reflection': typeof ApiFoundationReflectionRoute
  '/api/insights-generate': typeof ApiInsightsGenerateRoute
  '/api/spirals-analyze': typeof ApiSpiralsAnalyzeRoute
  '/api/vault-suggest': typeof ApiVaultSuggestRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/public/hooks/notification-opened': typeof ApiPublicHooksNotificationOpenedRoute
  '/api/public/hooks/refresh-custom-deals': typeof ApiPublicHooksRefreshCustomDealsRoute
  '/api/public/hooks/send-notifications': typeof ApiPublicHooksSendNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ace': typeof AuthenticatedAceRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/foundation': typeof AuthenticatedFoundationRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/nourish': typeof AuthenticatedNourishRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spirals': typeof AuthenticatedSpiralsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/api/ace': typeof ApiAceRoute
  '/api/foundation-reflection': typeof ApiFoundationReflectionRoute
  '/api/insights-generate': typeof ApiInsightsGenerateRoute
  '/api/spirals-analyze': typeof ApiSpiralsAnalyzeRoute
  '/api/vault-suggest': typeof ApiVaultSuggestRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/public/hooks/notification-opened': typeof ApiPublicHooksNotificationOpenedRoute
  '/api/public/hooks/refresh-custom-deals': typeof ApiPublicHooksRefreshCustomDealsRoute
  '/api/public/hooks/send-notifications': typeof ApiPublicHooksSendNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ace': typeof AuthenticatedAceRoute
  '/_authenticated/brain': typeof AuthenticatedBrainRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/foundation': typeof AuthenticatedFoundationRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/nourish': typeof AuthenticatedNourishRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spirals': typeof AuthenticatedSpiralsRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/api/ace': typeof ApiAceRoute
  '/api/foundation-reflection': typeof ApiFoundationReflectionRoute
  '/api/insights-generate': typeof ApiInsightsGenerateRoute
  '/api/spirals-analyze': typeof ApiSpiralsAnalyzeRoute
  '/api/vault-suggest': typeof ApiVaultSuggestRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/public/hooks/notification-opened': typeof ApiPublicHooksNotificationOpenedRoute
  '/api/public/hooks/refresh-custom-deals': typeof ApiPublicHooksRefreshCustomDealsRoute
  '/api/public/hooks/send-notifications': typeof ApiPublicHooksSendNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/handbook'
    | '/login'
    | '/sitemap.xml'
    | '/ace'
    | '/brain'
    | '/dashboard'
    | '/foundation'
    | '/insights'
    | '/integrations'
    | '/nourish'
    | '/onboarding'
    | '/settings'
    | '/spirals'
    | '/vault'
    | '/api/ace'
    | '/api/foundation-reflection'
    | '/api/insights-generate'
    | '/api/spirals-analyze'
    | '/api/vault-suggest'
    | '/api/gocardless/callback'
    | '/api/public/hooks/notification-opened'
    | '/api/public/hooks/refresh-custom-deals'
    | '/api/public/hooks/send-notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handbook'
    | '/login'
    | '/sitemap.xml'
    | '/ace'
    | '/brain'
    | '/dashboard'
    | '/foundation'
    | '/insights'
    | '/integrations'
    | '/nourish'
    | '/onboarding'
    | '/settings'
    | '/spirals'
    | '/vault'
    | '/api/ace'
    | '/api/foundation-reflection'
    | '/api/insights-generate'
    | '/api/spirals-analyze'
    | '/api/vault-suggest'
    | '/api/gocardless/callback'
    | '/api/public/hooks/notification-opened'
    | '/api/public/hooks/refresh-custom-deals'
    | '/api/public/hooks/send-notifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/handbook'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/ace'
    | '/_authenticated/brain'
    | '/_authenticated/dashboard'
    | '/_authenticated/foundation'
    | '/_authenticated/insights'
    | '/_authenticated/integrations'
    | '/_authenticated/nourish'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/spirals'
    | '/_authenticated/vault'
    | '/api/ace'
    | '/api/foundation-reflection'
    | '/api/insights-generate'
    | '/api/spirals-analyze'
    | '/api/vault-suggest'
    | '/api/gocardless/callback'
    | '/api/public/hooks/notification-opened'
    | '/api/public/hooks/refresh-custom-deals'
    | '/api/public/hooks/send-notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HandbookRoute: typeof HandbookRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAceRoute: typeof ApiAceRoute
  ApiFoundationReflectionRoute: typeof ApiFoundationReflectionRoute
  ApiInsightsGenerateRoute: typeof ApiInsightsGenerateRoute
  ApiSpiralsAnalyzeRoute: typeof ApiSpiralsAnalyzeRoute
  ApiVaultSuggestRoute: typeof ApiVaultSuggestRoute
  ApiGocardlessCallbackRoute: typeof ApiGocardlessCallbackRoute
  ApiPublicHooksNotificationOpenedRoute: typeof ApiPublicHooksNotificationOpenedRoute
  ApiPublicHooksRefreshCustomDealsRoute: typeof ApiPublicHooksRefreshCustomDealsRoute
  ApiPublicHooksSendNotificationsRoute: typeof ApiPublicHooksSendNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault-suggest': {
      id: '/api/vault-suggest'
      path: '/api/vault-suggest'
      fullPath: '/api/vault-suggest'
      preLoaderRoute: typeof ApiVaultSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spirals-analyze': {
      id: '/api/spirals-analyze'
      path: '/api/spirals-analyze'
      fullPath: '/api/spirals-analyze'
      preLoaderRoute: typeof ApiSpiralsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights-generate': {
      id: '/api/insights-generate'
      path: '/api/insights-generate'
      fullPath: '/api/insights-generate'
      preLoaderRoute: typeof ApiInsightsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foundation-reflection': {
      id: '/api/foundation-reflection'
      path: '/api/foundation-reflection'
      fullPath: '/api/foundation-reflection'
      preLoaderRoute: typeof ApiFoundationReflectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ace': {
      id: '/api/ace'
      path: '/api/ace'
      fullPath: '/api/ace'
      preLoaderRoute: typeof ApiAceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spirals': {
      id: '/_authenticated/spirals'
      path: '/spirals'
      fullPath: '/spirals'
      preLoaderRoute: typeof AuthenticatedSpiralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nourish': {
      id: '/_authenticated/nourish'
      path: '/nourish'
      fullPath: '/nourish'
      preLoaderRoute: typeof AuthenticatedNourishRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/foundation': {
      id: '/_authenticated/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof AuthenticatedFoundationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brain': {
      id: '/_authenticated/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AuthenticatedBrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ace': {
      id: '/_authenticated/ace'
      path: '/ace'
      fullPath: '/ace'
      preLoaderRoute: typeof AuthenticatedAceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/gocardless/callback': {
      id: '/api/gocardless/callback'
      path: '/api/gocardless/callback'
      fullPath: '/api/gocardless/callback'
      preLoaderRoute: typeof ApiGocardlessCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-notifications': {
      id: '/api/public/hooks/send-notifications'
      path: '/api/public/hooks/send-notifications'
      fullPath: '/api/public/hooks/send-notifications'
      preLoaderRoute: typeof ApiPublicHooksSendNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-custom-deals': {
      id: '/api/public/hooks/refresh-custom-deals'
      path: '/api/public/hooks/refresh-custom-deals'
      fullPath: '/api/public/hooks/refresh-custom-deals'
      preLoaderRoute: typeof ApiPublicHooksRefreshCustomDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-opened': {
      id: '/api/public/hooks/notification-opened'
      path: '/api/public/hooks/notification-opened'
      fullPath: '/api/public/hooks/notification-opened'
      preLoaderRoute: typeof ApiPublicHooksNotificationOpenedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAceRoute: typeof AuthenticatedAceRoute
  AuthenticatedBrainRoute: typeof AuthenticatedBrainRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFoundationRoute: typeof AuthenticatedFoundationRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedNourishRoute: typeof AuthenticatedNourishRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpiralsRoute: typeof AuthenticatedSpiralsRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAceRoute: AuthenticatedAceRoute,
  AuthenticatedBrainRoute: AuthenticatedBrainRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFoundationRoute: AuthenticatedFoundationRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedNourishRoute: AuthenticatedNourishRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpiralsRoute: AuthenticatedSpiralsRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HandbookRoute: HandbookRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAceRoute: ApiAceRoute,
  ApiFoundationReflectionRoute: ApiFoundationReflectionRoute,
  ApiInsightsGenerateRoute: ApiInsightsGenerateRoute,
  ApiSpiralsAnalyzeRoute: ApiSpiralsAnalyzeRoute,
  ApiVaultSuggestRoute: ApiVaultSuggestRoute,
  ApiGocardlessCallbackRoute: ApiGocardlessCallbackRoute,
  ApiPublicHooksNotificationOpenedRoute: ApiPublicHooksNotificationOpenedRoute,
  ApiPublicHooksRefreshCustomDealsRoute: ApiPublicHooksRefreshCustomDealsRoute,
  ApiPublicHooksSendNotificationsRoute: ApiPublicHooksSendNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
